### ISSUE TITLE
Get more specific information from DigIn people

### ISSUE THREAD

**Issue by mhoc** [dig-in-app/management#32]
- Locations of every participant
- Geographic locations of each tent
- Schedule
- Food menu
- Graphics (icon)

**Comment by vidia** [comment]
Contacted and awaiting response.

**Comment by mhoc** [comment]
Received response with rudimentary data. I will wait until we get the passport from them hopefully this or next week before loading anything else into parse.

**Comment by mhoc** [comment]
Closed as fixed.
